version: "3.8"
services:
  backend:
    build: .
    container_name: flask_backend
    ports:
      - "5000:5000"
    networks:
      - app_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "8080:3000"
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
